authors:

  kommandant:
    name: Karl-Heinz Köberer
    description: Kommandant
    avatar: https://github.com/odin568.png
  verein:
    name: Achim Hummel
    description: Verein
    avatar: https://github.com/odin568.png
  webmaster:
    name: Markus Zellner
    description: Webmaster
    avatar: https://github.com/odin568.png
