authors:
  webmaster:
    name: Markus Zellner
    description: Webmaster
    avatar: https://github.com/odin568.png
  kommandant:
    name: Karl-Heinz Köberer
    description: Kommandant
    avatar: https://github.com/alexvoss.png
