authors:

  kommandant:
    name: Karl-Heinz Köberer
    description: Kommandant
    avatar: https://ffw-baudenbach.github.io/Homepage/assets/avatar_koeberer.png
  verein:
    name: Achim Hummel
    description: Verein
    avatar: https://ffw-baudenbach.github.io/Homepage/assets/avatar_hummel.png
  webmaster:
    name: Markus Zellner
    description: Webmaster
    avatar: https://ffw-baudenbach.github.io/Homepage/assets/avatar_zellner.png
