authors:
  kommandant:
    name: Karl-Heinz Köberer
    description: Kommandant
    avatar: assets/avatar_koeberer.png
  verein_hummel:
    name: Achim Hummel
    description: Verein
    avatar: assets/avatar_hummel.png
  verein_beihl:
    name: Johannes Beihl
    description: Verein
    avatar: assets/avatar_beihl.png
  webmaster:
    name: Markus Zellner
    description: Webmaster
    avatar: assets/avatar_zellner.png
